version: "3.8"
services:
  go-api:
    container_name: go-api
    hostname: api
    build:
      context: .
      dockerfile: .docker/api/Dockerfile
    ports:
      - 3333:3333
    volumes:
      - ./api:/go/src/elasticsearch-golang-project
    depends_on: 
      - elasticsearch
    networks:
      - elasticnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - node.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - data_es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elasticnet

volumes:
  data_es:
    driver: local

networks:
  elasticnet:
    driver: bridge